# Generated by Django 4.0 on 2023-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='params',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
